import {
  MD3DarkTheme,
  MD3LightTheme,
  MD3Theme,
  configureFonts,
} from "react-native-paper";
import {
  DefaultTheme as NavDefaultTheme,
  DarkTheme as NavDarkTheme,
} from "@react-navigation/native";

export const darkTheme = {
  ...MD3DarkTheme,
  fonts: configureFonts({
    isV3: true,
  }),
  colors: {
    ...MD3DarkTheme.colors,
    primary: "#AFC6FF",
    surfaceTint: "#AFC6FF",
    onPrimary: "#142F60",
    primaryContainer: "#2D4578",
    onPrimaryContainer: "#D9E2FF",
    secondary: "#BFC6DC",
    onSecondary: "#293042",
    secondaryContainer: "#404659",
    onSecondaryContainer: "#DBE2F9",
    tertiary: "#DFBBDE",
    onTertiary: "#412742",
    tertiaryContainer: "#593E5A",
    onTertiaryContainer: "#FDD7FB",
    error: "#FFB4AB",
    onError: "#690005",
    errorContainer: "#93000A",
    onErrorContainer: "#FFDAD6",
    background: "#121318",
    onBackground: "#E2E2E9",
    surface: "#121318",
    onSurface: "#E2E2E9",
    surfaceVariant: "#44464F",
    onSurfaceVariant: "#C5C6D0",
    outline: "#8F9099",
    outlineVariant: "#44464F",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#E2E2E9",
    inverseOnSurface: "#2F3036",
    inversePrimary: "#465D91",
    primaryFixed: "#D9E2FF",
    onPrimaryFixed: "#001944",
    primaryFixedDim: "#AFC6FF",
    onPrimaryFixedVariant: "#2D4578",
    secondaryFixed: "#DBE2F9",
    onSecondaryFixed: "#141B2C",
    secondaryFixedDim: "#BFC6DC",
    onSecondaryFixedVariant: "#404659",
    tertiaryFixed: "#FDD7FB",
    onTertiaryFixed: "#2A132C",
    tertiaryFixedDim: "#DFBBDE",
    onTertiaryFixedVariant: "#593E5A",
    surfaceDim: "#121318",
    surfaceBright: "#38393E",
    surfaceContainerLowest: "#0C0E13",
    surfaceContainerLow: "#1A1B20",
    surfaceContainer: "#1E1F25",
    surfaceContainerHigh: "#282A2F",
    surfaceContainerHighest: "#33353A",
  },
};

export const lightTheme = {
  ...MD3LightTheme,
  fonts: configureFonts({
    isV3: true,
  }),
  colors: {
    ...MD3LightTheme.colors,
    primary: "#465D91",
    surfaceTint: "#465D91",
    onPrimary: "#FFFFFF",
    primaryContainer: "#D9E2FF",
    onPrimaryContainer: "#2D4578",
    secondary: "#575E71",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#DBE2F9",
    onSecondaryContainer: "#404659",
    tertiary: "#725573",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#FDD7FB",
    onTertiaryContainer: "#593E5A",
    error: "#BA1A1A",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#93000A",
    background: "#FAF8FF",
    onBackground: "#1A1B20",
    surface: "#FAF8FF",
    onSurface: "#1A1B20",
    surfaceVariant: "#E1E2EC",
    onSurfaceVariant: "#44464F",
    outline: "#757780",
    outlineVariant: "#C5C6D0",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#2F3036",
    inverseOnSurface: "#F1F0F7",
    inversePrimary: "#AFC6FF",
    primaryFixed: "#D9E2FF",
    onPrimaryFixed: "#001944",
    primaryFixedDim: "#AFC6FF",
    onPrimaryFixedVariant: "#2D4578",
    secondaryFixed: "#DBE2F9",
    onSecondaryFixed: "#141B2C",
    secondaryFixedDim: "#BFC6DC",
    onSecondaryFixedVariant: "#404659",
    tertiaryFixed: "#FDD7FB",
    onTertiaryFixed: "#2A132C",
    tertiaryFixedDim: "#DFBBDE",
    onTertiaryFixedVariant: "#593E5A",
    surfaceDim: "#DAD9E0",
    surfaceBright: "#FAF8FF",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#F4F3FA",
    surfaceContainer: "#EEEDF4",
    surfaceContainerHigh: "#E8E7EF",
    surfaceContainerHighest: "#E2E2E9",
  },
};

// Mapeamos el tema de Paper al tema de React Navigation
// para que los headers y fondos de la navegación coincidan con el Design System.
export const navigationLightTheme = {
  ...NavDefaultTheme,
  colors: {
    ...NavDefaultTheme.colors,
    primary: lightTheme.colors.primary,
    background: lightTheme.colors.background,
    card: lightTheme.colors.background,
    text: lightTheme.colors.onSurface,
    border: lightTheme.colors.outline,
    notification: lightTheme.colors.error,
  },
};

export const navigationDarkTheme = {
  ...NavDarkTheme,
  colors: {
    ...NavDarkTheme.colors,
    primary: darkTheme.colors.primary,
    background: darkTheme.colors.background,
    card: darkTheme.colors.surface,
    text: darkTheme.colors.onSurface,
    border: darkTheme.colors.outline,
    notification: darkTheme.colors.error,
  },
};
